version: "3"
services:
  mongodb:
    image: mongo
    container_name: todo_mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: todo
      MONGO_INITDB_ROOT_PASSWORD: Hello@123$$
      MONGO_INITDB_DATABASE: todo

    ports:
      - 27017:27017
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
